version: '3.7'

services:

  dbpitapalapi:
    image: dbpitapalapi
    restart: unless-stopped
    container_name: dbpitapalapi
    build: ./node/
    ports:
      - 3306:3306
      
  mysqlpitapal:
    image: mysqlpitapal
    restart: unless-stopped
    container_name: mysqlpitapal
    environment:
      MYSQL_ROOT_PASSWORD: password
    build: ./database/
    ports:
      - 3009:3009
      
networks:
  default:
    external:
      name: my-net